import type { Tool } from '../types';

export const TOOLS: Tool[] = [
  {
    id: 'lexscam',
    name: 'LexScam',
    tagline: 'Scam & fraud detector',
    description: 'Paste any suspicious message, job offer, investment pitch, or email. Get an instant verdict with every red flag quoted — before you click, pay, or reply.',
    icon: 'ShieldAlert',
    color: 'bg-rose-50',
    inputType: 'textarea',
    inputLabel: 'Paste the suspicious content or upload a screenshot',
    inputPlaceholder: 'Paste the full message, email, job offer, or investment pitch here...',
    price: 1,
    quiz: [
      {
        id: 'content',
        question: 'Paste the full message, email, or content you want to check.',
        fieldLabel: 'Content to analyze',
        type: 'textarea',
        placeholder: 'Paste the entire message, email, job offer, investment pitch, or description of the screenshot here. The more complete, the more accurate the verdict.',
        required: true,
      },
      {
        id: 'platform',
        question: 'Where or how did this reach you?',
        fieldLabel: 'Platform received on',
        type: 'select',
        options: [
          'Telegram',
          'WhatsApp',
          'Email',
          'Instagram / Facebook',
          'Dating app',
          'LinkedIn',
          'SMS / phone',
          'I found it myself',
        ],
        required: true,
      },
      {
        id: 'sender',
        question: 'Who is the sender claiming to be?',
        fieldLabel: 'Sender claims to be',
        type: 'select',
        options: [
          'Unknown individual',
          'A company or recruiter',
          'Someone claiming to know me',
          'A government or official body',
          'A crypto project, investor, or influencer',
          'A romantic interest',
          'Not clear',
        ],
        required: true,
      },
      {
        id: 'asks',
        question: 'What is it asking you to do?',
        fieldLabel: 'Action requested',
        type: 'multiselect',
        options: [
          'Click a link',
          'Send money or crypto',
          'Share personal details or ID documents',
          'Download something',
          'Pay a fee upfront',
          'Create an account',
          'Share my login or password',
          'Nothing specific yet — just feels off',
        ],
        required: true,
      },
      {
        id: 'already_acted',
        question: 'Have you already clicked, paid, or shared anything?',
        fieldLabel: 'Actions already taken',
        type: 'select',
        options: [
          'No — I have not done anything yet',
          'I clicked a link',
          'I shared personal details or ID',
          'I sent money or crypto',
          'I downloaded something',
          'Multiple of the above',
        ],
        required: true,
      },
    ],
    templates: [
      {
        label: '💼 Suspicious job offer',
        text: 'I received this job offer and want to check if it is a scam.\n\nReceived via: [Telegram / email / LinkedIn / other]\nSender claims to be: [recruiter name, company name]\n\nFull message:\n[paste the complete message here]\n\nWhat they are asking me to do: [e.g. pay for training / share ID / click a link]\nHave I already responded or paid? [yes / no]',
      },
      {
        label: '💰 Crypto / investment pitch',
        text: 'I received an investment or crypto opportunity and want to check if it is a scam.\n\nReceived via: [Telegram / WhatsApp / email / social media]\nSender claims to be: [name / platform name / influencer]\n\nFull message or pitch:\n[paste the complete content here]\n\nWhat they promise: [e.g. guaranteed returns / exclusive opportunity / limited time]\nWhat they are asking me to do: [e.g. send crypto / deposit money / sign up on a platform]\nHave I already sent anything? [yes / no — if yes, how much]',
      },
      {
        label: '💬 Suspicious message',
        text: 'I received this message and am not sure if it is a scam.\n\nReceived via: [Telegram / WhatsApp / SMS / email / dating app]\nSender: [unknown / someone claiming to know me / official-looking account]\n\nFull message:\n[paste the complete message here]\n\nWhat it is asking me to do: [describe]\nAnything that felt suspicious: [describe what caught your attention]',
      },
    ],
  },
  {
    id: 'lexcompare',
    name: 'LexCompare',
    tagline: 'What changed in this contract?',
    description: 'Upload two versions of a contract (old vs new). Get a diff that names every change, flags which side it favours, and tells you whether to sign, negotiate, or walk away.',
    icon: 'GitCompareArrows',
    color: 'bg-violet-50',
    inputType: 'textarea',
    inputLabel: 'Anything you want LexCompare to know (optional)',
    inputPlaceholder: 'Optional context, e.g. "This is my employment contract renewal — the company says it is just a formal update with no material changes."',
    price: 2,
    dualFile: true,
    dualFileLabels: { first: 'Old / current version', second: 'New / proposed version' },
    templates: [
      {
        label: '📄 Lease renewal',
        text: 'My landlord sent me a new lease for the renewal. They said the changes are minor. I want to know what is actually different from the version I am currently signed to.',
      },
      {
        label: '💼 Employment contract renewal',
        text: 'My employer is asking me to sign an updated employment contract. I want to know exactly what changed — pay, notice period, non-compete, IP, anything that affects me.',
      },
      {
        label: '🤝 SaaS / service agreement renewal',
        text: 'Our vendor sent a renewal of our service agreement. I want to know what changed in pricing, term, auto-renewal, liability, and SLA.',
      },
      {
        label: '🛡️ Insurance policy renewal',
        text: 'My insurer sent a renewal policy. I want to know what cover, exclusions, excess, or premium structure changed compared to the previous year.',
      },
    ],
  },
  {
    id: 'signsafe',
    name: 'SignSafe',
    tagline: 'Contract risk scanner',
    description: 'Paste any contract and get a plain-language breakdown of dangerous clauses, hidden fees, and what you are actually signing away.',
    icon: 'FileText',
    color: 'bg-emerald-50',
    inputType: 'textarea',
    inputLabel: 'Paste your contract text or upload the document',
    inputPlaceholder: 'Paste the full contract here, or upload a photo/PDF above...',
    price: 1,
    quiz: [
      {
        id: 'contract_type',
        question: 'What type of contract is this?',
        fieldLabel: 'Contract type',
        type: 'select',
        options: [
          'Employment contract',
          'Rental / tenancy agreement',
          'Freelance / contractor agreement',
          'Service agreement',
          'NDA (Non-Disclosure Agreement)',
          'Business partnership agreement',
          'Loan agreement',
          'Other',
        ],
        required: true,
      },
      {
        id: 'jurisdiction',
        question: 'Which country or jurisdiction governs this contract?',
        fieldLabel: 'Jurisdiction',
        type: 'text',
        placeholder: 'e.g. United Kingdom, Germany, New York (US)',
        required: true,
      },
      {
        id: 'contract_value',
        question: 'What is the value of this contract?',
        fieldLabel: 'Contract value',
        type: 'text',
        placeholder: 'e.g. £45,000/year salary, €1,200/month rent, one-off €5,000 project',
        required: false,
      },
      {
        id: 'duration',
        question: 'How long does the contract run?',
        fieldLabel: 'Duration',
        type: 'select',
        options: [
          'Permanent / ongoing',
          'Fixed-term — under 1 year',
          'Fixed-term — 1 to 3 years',
          'Fixed-term — over 3 years',
          'Not specified in the contract',
        ],
        required: true,
      },
      {
        id: 'concerns',
        question: 'Which clauses concern you most?',
        fieldLabel: 'Clauses of concern',
        type: 'multiselect',
        options: [
          'Non-compete or restrictive covenant',
          'Intellectual property ownership',
          'Termination conditions',
          'Liability or indemnity',
          'Payment terms or hidden fees',
          'Auto-renewal or lock-in',
          'Data privacy or sharing',
          'Not sure — full review needed',
        ],
        required: true,
      },
      {
        id: 'specific_clause',
        question: 'Is there a specific clause you want highlighted?',
        fieldLabel: 'Specific clause to review',
        type: 'textarea',
        placeholder: 'Paste the exact wording of a clause you are unsure about, or leave blank for a full general review',
        required: false,
      },
      {
        id: 'context',
        question: 'Any other context that might be relevant?',
        fieldLabel: 'Additional context',
        type: 'text',
        placeholder: 'e.g. I cannot negotiate terms, this is my first job, the company is a startup',
        required: false,
      },
    ],
    templates: [
      {
        label: '💼 Employment contract',
        text: 'I am about to sign an employment contract and need a full risk analysis.\n\nCountry / jurisdiction: [COUNTRY]\nRole: [JOB TITLE] at a [startup / mid-size / corporate] company\nSalary: [AMOUNT + currency], [permanent / fixed-term]\nProbation period: [X months]\nNotice period: [X weeks/months]\n\nKey clauses I am concerned about:\n- Non-compete clause: [yes / no — if yes, duration and scope]\n- IP ownership: [does the contract claim rights to work done outside hours?]\n- Termination conditions: [describe any unusual terms]\n- Other clauses that seem unusual: [describe]\n\nMy main concern: [what specifically worries you about this contract?]',
      },
      {
        label: '🏠 Rental agreement',
        text: 'I am about to sign a rental lease and need a full risk analysis.\n\nCountry / city: [COUNTRY, CITY]\nMonthly rent: [AMOUNT + currency]\nDeposit amount: [AMOUNT — how many months rent?]\nLease duration: [X months, fixed-term / rolling]\nProperty type: [apartment / house / room]\n\nClauses I am concerned about:\n- Rent increase terms: [describe — e.g. landlord can raise by X% every Y months]\n- Repair responsibilities: [what does the contract say the tenant must pay for?]\n- Guest / subletting restrictions: [describe]\n- Early termination: [what penalty if I leave early?]\n- Any other unusual terms: [describe]\n\nMy main concern: [what specifically worries you?]',
      },
      {
        label: '🤝 Freelance contract',
        text: 'I am signing a freelance / independent contractor agreement and need a full risk analysis.\n\nCountry / jurisdiction: [COUNTRY]\nMy role: [freelancer / contractor]\nClient type: [agency / startup / corporation]\nProject: [describe the work briefly]\nTotal fee: [AMOUNT + currency]\nPayment terms: [upfront / milestone / on delivery / NET 30]\nProject duration: [X weeks/months]\n\nClauses I am concerned about:\n- Revision / change requests: [unlimited? capped?]\n- IP / copyright ownership: [when does it transfer? any conditions?]\n- Liability clause: [any indemnification or limitation of liability?]\n- Dispute resolution: [court / arbitration / which jurisdiction?]\n- Non-solicitation or non-compete: [yes / no]\n\nMy main concern: [what specifically worries you?]',
      },
    ],
  },
  {
    id: 'finebot',
    name: 'FineBot',
    tagline: 'Dispute any fine or ticket',
    description: 'Got a parking ticket or admin penalty? Get a ready-to-send dispute letter tailored to your jurisdiction in under 60 seconds.',
    icon: 'AlertTriangle',
    color: 'bg-amber-50',
    inputType: 'form',
    inputLabel: 'Describe your fine or upload a photo of it',
    inputPlaceholder: 'e.g. Parking fine, €80, issued in Lisbon Portugal on 15 May 2026. I was parked for 10 minutes while unloading...',
    price: 1,
    quiz: [
      {
        id: 'fine_type',
        question: 'What type of fine or penalty did you receive?',
        fieldLabel: 'Type of fine',
        type: 'select',
        options: [
          'Parking fine',
          'Speed camera fine',
          'Bus lane or red-light violation',
          'Traffic violation by an officer',
          'Administrative penalty (from a government body)',
          'Congestion / emissions zone charge',
          'Other',
        ],
        required: true,
      },
      {
        id: 'location',
        question: 'Where was the fine issued?',
        fieldLabel: 'Country and city',
        type: 'text',
        placeholder: 'e.g. Portugal, Lisbon — or Germany, Munich',
        required: true,
      },
      {
        id: 'amount',
        question: 'How much is the fine?',
        fieldLabel: 'Fine amount',
        type: 'text',
        placeholder: 'e.g. €80 or £120 + 3 penalty points',
        required: true,
      },
      {
        id: 'issuing_authority',
        question: 'Who issued the fine?',
        fieldLabel: 'Issuing authority',
        type: 'select',
        options: [
          'Municipal / city police',
          'National traffic authority',
          'Private enforcement company',
          'Tax or customs authority',
          'Environmental or other government agency',
          'Not sure',
        ],
        required: true,
      },
      {
        id: 'deadline',
        question: 'What is the appeal or payment deadline?',
        fieldLabel: 'Deadline to respond',
        type: 'text',
        placeholder: 'e.g. 14 days from issue date, or a specific date like 10 June 2026',
        required: false,
      },
      {
        id: 'what_happened',
        question: 'What actually happened? Describe in your own words.',
        fieldLabel: 'What actually happened',
        type: 'textarea',
        placeholder: 'Describe the situation — what you were doing, how long, any mitigating factors, anything unusual about the location or signage',
        required: true,
      },
      {
        id: 'grounds',
        question: 'What grounds do you have to dispute it?',
        fieldLabel: 'Grounds for dispute',
        type: 'multiselect',
        options: [
          'Signage was unclear or missing',
          'I was not the driver at the time',
          'Procedural error on the notice',
          'Emergency or medical circumstances',
          'I had a valid permit or exemption',
          'Camera error or calibration issue',
          'The fine was already paid or resolved',
          'Other',
        ],
        required: true,
      },
      {
        id: 'evidence',
        question: 'What evidence do you have?',
        fieldLabel: 'Evidence available',
        type: 'multiselect',
        options: [
          'Photos of the scene or signage',
          'Dashcam footage',
          'Witness who can confirm',
          'Parking receipt or permit',
          'Medical or emergency document',
          'GPS or phone location data',
          'None yet',
        ],
        required: true,
      },
    ],
    templates: [
      {
        label: '🚗 Parking / traffic fine',
        text: 'I received a fine and want to dispute it.\n\nCountry / city: [COUNTRY, CITY]\nFine type: [parking / speeding / traffic violation / bus lane / other]\nFine amount: [AMOUNT + currency]\nIssuing authority: [e.g. municipal police / traffic authority / private company]\nDate issued: [DATE]\nAppeal deadline: [DATE or X days shown on notice]\n\nOfficial reason stated on notice: [copy the exact wording]\n\nWhat actually happened: [describe the full situation — what you were doing, how long you were there, any mitigating factors]\n\nGrounds I believe I have to dispute it:\n- [e.g. signage was unclear / I was not the driver / procedural error on notice / emergency circumstances]\n\nEvidence I have: [photos / dashcam / witness / receipt / medical document / other]',
      },
      {
        label: '📷 Speed camera fine',
        text: 'I received a speed camera fine and want to challenge it.\n\nCountry: [COUNTRY]\nFine amount: [AMOUNT + currency]\nPenalty points: [X points, if applicable]\nAlleged speed: [X km/h or mph] in a [Y] zone\nDate of alleged offence: [DATE]\nDeadline to respond: [DATE or X days]\nI am: [the driver / the registered owner but not the driver]\n\nWhy I believe the fine is wrong:\n- [e.g. I was not speeding / I was not the driver at the time / camera location is disputed / calibration concerns / signs were not visible]\n\nEvidence I have: [dashcam footage / alibi / witness / GPS data / other]',
      },
      {
        label: '📋 Administrative penalty',
        text: 'I received an administrative fine or penalty from a government authority and want to contest it.\n\nCountry: [COUNTRY]\nIssuing authority: [e.g. tax office / environmental agency / labour inspectorate / municipality]\nFine amount: [AMOUNT + currency]\nReason stated: [describe what the authority claims you violated]\nDate issued: [DATE]\nDeadline to contest: [DATE or X days]\n\nWhy I believe the penalty is unjust or disproportionate:\n- [e.g. I was not aware of the requirement / I had already complied / the rule was applied incorrectly / procedural error]\n\nPrior communication with the authority: [yes / no — if yes, describe]\nEvidence I have: [documents / correspondence / receipts / permits / other]',
      },
    ],
  },
  {
    id: 'tenantshield',
    name: 'TenantShield',
    tagline: 'Know your rental rights',
    description: 'Describe your landlord issue and get your exact legal rights plus a templated demand letter.',
    icon: 'Home',
    color: 'bg-purple-50',
    inputType: 'textarea',
    inputLabel: 'Describe your rental issue or upload evidence',
    inputPlaceholder: 'e.g. My landlord in Berlin refuses to return my €1200 deposit after I moved out 6 weeks ago...',
    price: 1,
    quiz: [
      {
        id: 'issue_type',
        question: 'What is your rental issue?',
        fieldLabel: 'Nature of issue',
        type: 'select',
        options: [
          'Landlord withholding my deposit',
          'Landlord refusing necessary repairs',
          'Threatened or unlawful eviction',
          'Unlawful rent increase',
          'Landlord harassment or entering without notice',
          'Other',
        ],
        required: true,
      },
      {
        id: 'location',
        question: 'Where is the property located?',
        fieldLabel: 'Country and city',
        type: 'text',
        placeholder: 'e.g. Germany, Berlin — or France, Paris',
        required: true,
      },
      {
        id: 'tenancy_length',
        question: 'How long have you been renting this property?',
        fieldLabel: 'Length of tenancy',
        type: 'select',
        options: [
          'Less than 6 months',
          '6 months to 1 year',
          '1 to 3 years',
          'More than 3 years',
        ],
        required: true,
      },
      {
        id: 'lease_type',
        question: 'What type of lease do you have?',
        fieldLabel: 'Lease type',
        type: 'select',
        options: [
          'Fixed-term (with a set end date)',
          'Rolling monthly (periodic)',
          'Verbal or informal agreement',
          'Not sure',
        ],
        required: true,
      },
      {
        id: 'rent_status',
        question: 'Is your rent fully up to date?',
        fieldLabel: 'Rent payment status',
        type: 'select',
        options: [
          'Yes, fully paid and up to date',
          'Slightly behind — less than 1 month',
          'More than 1 month behind',
        ],
        required: true,
      },
      {
        id: 'amounts',
        question: 'What are the relevant amounts?',
        fieldLabel: 'Amounts involved',
        type: 'text',
        placeholder: 'e.g. Monthly rent €900, deposit €1,800 (2 months), withheld amount €1,200',
        required: false,
      },
      {
        id: 'description',
        question: 'Describe the issue in detail.',
        fieldLabel: 'Issue description',
        type: 'textarea',
        placeholder: 'What specifically happened? What has your landlord said or done? How long has this been going on?',
        required: true,
      },
      {
        id: 'evidence',
        question: 'What evidence do you have?',
        fieldLabel: 'Evidence available',
        type: 'multiselect',
        options: [
          'Signed tenancy agreement',
          'Move-in / move-out inspection report',
          'Photos or video of the property',
          'Written communication (emails / messages)',
          'Bank transfer records',
          'Witness',
          'None',
        ],
        required: true,
      },
    ],
    templates: [
      {
        label: '💰 Deposit not returned',
        text: 'My landlord is refusing to return my deposit after I moved out.\n\nCountry / city: [COUNTRY, CITY]\nDeposit amount: [AMOUNT + currency]\nMove-out date: [DATE]\nTime since move-out: [X weeks]\nLease type: [fixed-term / rolling monthly]\nRent was: [fully up to date / X weeks overdue]\n\nCondition of property at move-out: [excellent / normal wear and tear / some damage — describe]\nDid you have a move-in / move-out inspection report? [yes / no]\nPhotos or evidence of condition: [yes / no]\n\nLandlord\'s reason for withholding: [describe exactly what they claim]\nDeductions they are demanding: [list each item and amount]\n\nCommunication so far: [describe — emails sent, responses received, how many weeks have passed]',
      },
      {
        label: '🔧 Landlord refusing repairs',
        text: 'My landlord is refusing to carry out necessary repairs to my rental property.\n\nCountry / city: [COUNTRY, CITY]\nType of tenancy: [private / social / student housing]\nMonthly rent: [AMOUNT + currency]\nLease remaining: [X months]\n\nProblem requiring repair: [describe in detail — e.g. broken heating, water leak, mould, structural issue, pest infestation]\nIs this affecting health or safety? [yes / no — describe impact]\nHow long has the problem existed? [X weeks / months]\n\nHow I notified the landlord:\n- [number of times, method: email / text / phone / letter, dates if known]\nLandlord\'s response: [ignored / promised to fix but did not / refused / offered inadequate solution]\n\nEvidence I have: [photos / written correspondence / medical records / other]',
      },
      {
        label: '🚪 Illegal eviction',
        text: 'My landlord is threatening to evict me or has taken action I believe is unlawful.\n\nCountry / city: [COUNTRY, CITY]\nTenancy duration: [X years / months]\nLease type: [fixed-term — expires DATE / rolling monthly]\nRent status: [fully up to date / X weeks overdue]\n\nWhat the landlord has done or threatened:\n- [e.g. verbally told me to leave / sent a letter / changed locks / removed belongings / cut off utilities]\n\nNotice given: [none / X days — was it written or verbal?]\nReason given by landlord: [e.g. wants property back / claims non-payment / selling property / other]\n\nWhy I believe this is unlawful: [describe your understanding]\nEvidence I have: [tenancy agreement / correspondence / photos / witness]\nIs this urgent (immediate threat)? [yes / no]',
      },
    ],
  },
  {
    id: 'lexsalary',
    name: 'LexSalary',
    tagline: 'Is my pay fair?',
    description: 'Describe your job, salary, hours, and country. Get an instant verdict — fair, below market, or illegal — with the exact number to ask for and the back-pay you may be owed.',
    icon: 'BadgeDollarSign',
    color: 'bg-emerald-50',
    inputType: 'textarea',
    inputLabel: 'Describe your role, salary, hours, and country',
    inputPlaceholder: 'e.g. Senior software engineer in Berlin, Germany. 5 years experience. €58,000/year gross, 40 hrs/week, no overtime pay...',
    price: 1,
    quiz: [
      {
        id: 'country',
        question: 'Which country are you working in?',
        fieldLabel: 'Country of employment',
        type: 'text',
        placeholder: 'e.g. Germany, United Kingdom, Romania, United States (California)',
        required: true,
      },
      {
        id: 'role',
        question: 'What is your job title?',
        fieldLabel: 'Job title',
        type: 'text',
        placeholder: 'e.g. Senior software engineer, HGV driver, registered nurse, marketing manager',
        required: true,
      },
      {
        id: 'industry',
        question: 'Which industry?',
        fieldLabel: 'Industry',
        type: 'select',
        options: [
          'Software / Tech / IT',
          'Finance / Banking / Insurance',
          'Healthcare / Medical',
          'Retail / Hospitality / Food service',
          'Transport / Logistics / Delivery',
          'Construction / Trades',
          'Manufacturing / Industrial',
          'Education / Public sector',
          'Marketing / Sales / Media',
          'Legal / Professional services',
          'Other',
        ],
        required: true,
      },
      {
        id: 'experience',
        question: 'How many years of experience do you have in this role?',
        fieldLabel: 'Years of experience',
        type: 'select',
        options: [
          'Less than 1 year (entry level)',
          '1–3 years (junior)',
          '3–5 years (mid level)',
          '5–10 years (senior)',
          '10–20 years (lead / principal)',
          '20+ years (expert)',
        ],
        required: true,
      },
      {
        id: 'salary',
        question: 'What is your gross salary? Include currency and frequency.',
        fieldLabel: 'Gross salary',
        type: 'text',
        placeholder: 'e.g. €58,000 per year gross, £3,200/month gross, $25/hour, 4,500 RON/month net',
        required: true,
      },
      {
        id: 'hours',
        question: 'How many hours per week do you actually work?',
        fieldLabel: 'Actual hours per week',
        type: 'select',
        options: [
          'Less than 20 hours (part-time)',
          '20–35 hours',
          '36–40 hours (standard)',
          '41–48 hours',
          '49–55 hours',
          '56+ hours',
        ],
        required: true,
      },
      {
        id: 'overtime',
        question: 'How is overtime handled?',
        fieldLabel: 'Overtime situation',
        type: 'select',
        options: [
          'I do not work overtime',
          'Overtime paid at standard rate',
          'Overtime paid at 1.5× or higher',
          'Overtime given as time off in lieu',
          'Overtime not paid at all',
          'Not sure',
        ],
        required: true,
      },
      {
        id: 'contract',
        question: 'What kind of contract are you on?',
        fieldLabel: 'Contract type',
        type: 'select',
        options: [
          'Full-time permanent employee',
          'Part-time permanent employee',
          'Fixed-term / temporary contract',
          'Self-employed / freelance / contractor',
          'Zero-hours / on-call',
          'Probation period',
          'No written contract',
        ],
        required: true,
      },
      {
        id: 'tenure',
        question: 'How long have you been in this job?',
        fieldLabel: 'Length of employment',
        type: 'select',
        options: [
          'Less than 3 months',
          '3–12 months',
          '1–2 years',
          '2–5 years',
          '5–10 years',
          '10+ years',
          'This is a job offer I am considering',
        ],
        required: true,
      },
      {
        id: 'extras',
        question: 'Any benefits or extras worth mentioning?',
        fieldLabel: 'Benefits and extras',
        type: 'textarea',
        placeholder: 'e.g. 13th-month bonus, private healthcare, 25 days holiday, stock options, meal vouchers, remote work — or "none" if there are none.',
        required: false,
      },
    ],
    templates: [
      {
        label: '💻 Tech / software role',
        text: 'I want to check if my software/tech salary is fair.\n\nCountry: [country]\nRole: [job title — e.g. backend engineer, data analyst]\nExperience: [years]\nSalary: [amount + currency + per year/month]\nHours per week: [actual hours worked]\nOvertime: [paid / unpaid / not applicable]\nBenefits: [stock, bonus, healthcare, holiday days]\nContract: [permanent / contractor / freelance]\nTenure: [how long at this company]',
      },
      {
        label: '🚛 Transport / driver role',
        text: 'I want to check if my pay as a driver is fair and legal.\n\nCountry: [country]\nRole: [HGV driver / delivery driver / taxi / etc.]\nExperience: [years]\nPay: [hourly rate or monthly + currency]\nHours per week: [actual hours]\nOvertime: [how it is paid]\nNight shifts / weekends: [included? paid extra?]\nContract: [employed / self-employed / agency]\nTenure: [how long]',
      },
      {
        label: '🏥 Healthcare / shift work',
        text: 'I want to check if my pay in healthcare is fair.\n\nCountry: [country]\nRole: [nurse / care worker / paramedic / etc.]\nExperience: [years + qualifications]\nBase salary: [amount + currency + per year/month]\nHours per week: [contracted vs actual]\nShift patterns: [nights / weekends — paid extras?]\nOvertime: [how handled]\nContract: [NHS / agency / private]\nTenure: [how long]',
      },
      {
        label: '📊 Generic salary check',
        text: 'I want to check if my compensation is fair.\n\nCountry: [country]\nRole: [job title]\nIndustry: [sector]\nExperience: [years]\nSalary: [amount + currency + per year/month gross or net]\nHours per week: [actual]\nOvertime situation: [paid / unpaid / not applicable]\nBenefits: [list anything significant]\nContract type: [permanent / fixed / contractor]\nTenure: [how long in this job]\nWhat I want to know: [is it fair, am I being underpaid, what should I ask for]',
      },
    ],
  },
  {
    id: 'workershield',
    name: 'WorkerShield',
    tagline: 'Employment rights checker',
    description: 'Describe what happened at work — wrongful termination, unpaid overtime, or harassment — and get a legal action plan.',
    icon: 'Briefcase',
    color: 'bg-blue-50',
    inputType: 'textarea',
    inputLabel: 'Describe your work situation or upload relevant documents',
    inputPlaceholder: 'e.g. I was fired by email with no notice after 3 years at the company in the UK...',
    price: 1,
    quiz: [
      {
        id: 'issue_type',
        question: 'What is your main workplace issue?',
        fieldLabel: 'Issue type',
        type: 'select',
        options: [
          'Wrongful or unfair dismissal',
          'Unpaid wages, overtime, or commission',
          'Harassment or discrimination',
          'Denied leave or benefits',
          'Forced or pressured resignation',
          'Unsafe working conditions',
          'Other',
        ],
        required: true,
      },
      {
        id: 'country',
        question: 'Which country are you employed in?',
        fieldLabel: 'Country',
        type: 'text',
        placeholder: 'e.g. United Kingdom, France, Australia',
        required: true,
      },
      {
        id: 'employment_type',
        question: 'What is your employment type?',
        fieldLabel: 'Employment type',
        type: 'select',
        options: [
          'Permanent employee',
          'Fixed-term contract',
          'Probationary period',
          'Zero-hours / casual',
          'Self-employed / contractor',
        ],
        required: true,
      },
      {
        id: 'duration',
        question: 'How long have you worked for this employer?',
        fieldLabel: 'Length of employment',
        type: 'select',
        options: [
          'Less than 3 months',
          '3 to 12 months',
          '1 to 3 years',
          'More than 3 years',
        ],
        required: true,
      },
      {
        id: 'still_employed',
        question: 'Are you still employed there?',
        fieldLabel: 'Current employment status',
        type: 'select',
        options: [
          'Yes, still employed',
          'No — I was dismissed',
          'No — I resigned',
          'No — my contract ended',
        ],
        required: true,
      },
      {
        id: 'description',
        question: 'Describe what happened in detail.',
        fieldLabel: 'What happened',
        type: 'textarea',
        placeholder: 'Include dates, what was said, who was involved, and the sequence of events',
        required: true,
      },
      {
        id: 'internal_action',
        question: 'Have you raised this internally?',
        fieldLabel: 'Internal complaint status',
        type: 'select',
        options: [
          'Yes — formal grievance or complaint filed',
          'Yes — raised informally with HR or a manager',
          'No — not yet',
        ],
        required: true,
      },
      {
        id: 'evidence',
        question: 'What evidence do you have?',
        fieldLabel: 'Evidence available',
        type: 'multiselect',
        options: [
          'Signed employment contract',
          'Termination letter',
          'Payslips',
          'Emails or messages',
          'Performance reviews',
          'Witness',
          'Medical records or sick notes',
          'None',
        ],
        required: true,
      },
    ],
    templates: [
      {
        label: '🔴 Wrongful termination',
        text: 'I was dismissed from my job and I believe it was unlawful.\n\nCountry: [COUNTRY]\nYears / months employed: [X]\nContract type: [permanent / fixed-term / probationary / zero-hours]\nRole: [JOB TITLE]\n\nHow I was dismissed: [in person / by letter / by email / verbally]\nNotice given: [none / X days — what does my contract specify?]\nOfficial reason given by employer: [exact wording if possible]\nPrior disciplinary warnings: [none / X warnings — describe]\n\nWhy I believe the dismissal was unlawful:\n- [e.g. no valid reason / discriminatory / retaliation for complaint / procedural breach / during protected period such as maternity/sick leave]\n\nDocumentation I have: [contract / termination letter / payslips / performance reviews / emails / other]\nHave I raised a grievance internally? [yes / no]\nTime since dismissal: [X days / weeks]',
      },
      {
        label: '⏰ Unpaid wages',
        text: 'My employer owes me money and is refusing to pay.\n\nCountry: [COUNTRY]\nEmployment type: [employed / contractor / zero-hours]\nAmount owed: approximately [AMOUNT + currency]\nType of unpaid amount: [overtime / withheld salary / unpaid bonus / commission / holiday pay / other]\nPeriod this covers: [DATE RANGE]\n\nHow the underpayment happened:\n- [e.g. hours recorded incorrectly / bonus conditions disputed / salary not paid at all / deductions made without consent]\n\nWhat my contract or agreement says about this: [describe the relevant terms]\nHave I raised this with HR or management? [yes / no — if yes, their response]\nEvidence I have: [payslips / timesheets / contract / emails / messages]\nIs my employment ongoing or have I left? [still employed / left on DATE]',
      },
      {
        label: '⚠️ Harassment / discrimination',
        text: 'I am experiencing harassment or discrimination at work and want to know my legal options.\n\nCountry: [COUNTRY]\nType of issue: [sexual harassment / racial discrimination / age discrimination / bullying / victimisation / other — describe]\nWho is responsible: [direct manager / colleague / HR / senior leadership]\nDuration: [X weeks / months]\n\nSpecific incidents (describe the most significant ones):\n1. [date, what happened, who was present]\n2. [date, what happened, who was present]\n\nHave you reported it internally? [yes / no]\nIf yes — to whom, when, and what was the response?\n\nEvidence I have: [emails / messages / witness names / medical records / HR correspondence]\nImpact on me: [describe — e.g. forced to resign / demoted / anxiety / sick leave]',
      },
    ],
  },
  {
    id: 'refundforce',
    name: 'RefundForce',
    tagline: 'Force a refund or chargeback',
    description: 'Describe your consumer dispute and get the exact legal template and escalation path to force a refund.',
    icon: 'Receipt',
    color: 'bg-red-50',
    inputType: 'textarea',
    inputLabel: 'Describe your consumer dispute or upload the receipt/invoice',
    inputPlaceholder: 'e.g. I bought a laptop from an online store in Italy 3 weeks ago. It arrived broken...',
    price: 1,
    quiz: [
      {
        id: 'issue_type',
        question: 'What happened?',
        fieldLabel: 'Type of dispute',
        type: 'select',
        options: [
          'Product is defective or not as described',
          'Item was never delivered',
          'Unauthorized or continuing charges',
          'Service was not provided as promised',
          'I cancelled but am still being charged',
          'Other',
        ],
        required: true,
      },
      {
        id: 'country',
        question: 'Which country are you in?',
        fieldLabel: 'Your country',
        type: 'text',
        placeholder: 'e.g. Italy, Spain, United States',
        required: true,
      },
      {
        id: 'merchant',
        question: 'Who is the merchant or company?',
        fieldLabel: 'Merchant / company',
        type: 'text',
        placeholder: 'e.g. Amazon UK, a local electronics store, a SaaS subscription service',
        required: true,
      },
      {
        id: 'amount',
        question: 'How much do you want refunded?',
        fieldLabel: 'Amount claimed',
        type: 'text',
        placeholder: 'e.g. €249.99 or £85 total across 3 months',
        required: true,
      },
      {
        id: 'payment_method',
        question: 'How did you pay?',
        fieldLabel: 'Payment method',
        type: 'select',
        options: [
          'Credit card — Visa',
          'Credit card — Mastercard',
          'Credit card — American Express',
          'Debit card',
          'PayPal',
          'Bank transfer',
          'Other',
        ],
        required: true,
      },
      {
        id: 'purchase_age',
        question: 'When did you make the purchase?',
        fieldLabel: 'Time since purchase',
        type: 'select',
        options: [
          'Less than 14 days ago',
          '14 to 30 days ago',
          '1 to 3 months ago',
          '3 to 6 months ago',
          'More than 6 months ago',
        ],
        required: true,
      },
      {
        id: 'seller_contact',
        question: 'Have you already contacted the merchant?',
        fieldLabel: 'Contact with merchant',
        type: 'select',
        options: [
          'No, not yet',
          'Yes — they refused a refund',
          'Yes — they did not respond',
          'Yes — they offered a partial refund only',
        ],
        required: true,
      },
      {
        id: 'description',
        question: 'Describe what happened in detail.',
        fieldLabel: 'Full situation',
        type: 'textarea',
        placeholder: 'Include what you ordered, what went wrong, what the seller said, and what outcome you are seeking',
        required: true,
      },
    ],
    templates: [
      {
        label: '📦 Defective product',
        text: 'I purchased a product that is defective or not as described and the seller is refusing to help.\n\nCountry: [COUNTRY]\nSeller type: [online retailer / physical store / marketplace like Amazon/eBay]\nSeller location: [same country / different country — specify]\nProduct: [describe item]\nPurchase price: [AMOUNT + currency]\nPurchase date: [DATE]\nPayment method: [credit card / debit card / PayPal / bank transfer — card type if known]\n\nDefect / problem: [describe exactly what is wrong]\nWhen defect appeared: [on arrival / after X days of use]\nDid you report it to the seller? [yes — on DATE / no]\nSeller\'s response: [refused / offered repair only / blamed me / no response]\n\nEvidence I have: [photos / videos / delivery photos / written seller response / other]\nHave you already attempted a return? [yes / no — describe outcome]',
      },
      {
        label: '🚚 Item not delivered',
        text: 'I paid for a product or service that was never delivered and I want my money back.\n\nCountry: [COUNTRY]\nSeller / company: [NAME and website if online]\nSeller location: [same country / abroad — specify]\nAmount paid: [AMOUNT + currency]\nPayment method: [credit card / debit card / PayPal / bank transfer — card type if known]\nOrder date: [DATE]\nPromised delivery date: [DATE]\n\nCurrent situation: [tracking stuck / no tracking provided / seller says it was delivered but I never received it / seller went silent]\nTime since expected delivery: [X weeks]\n\nCommunication with seller:\n- [number of contacts, dates, what they said]\n\nWhat I want: [full refund / reshipment]\nHave you opened a dispute with PayPal or your bank yet? [yes / no]',
      },
      {
        label: '🔄 Unauthorised charges',
        text: 'A company is charging me for a subscription or service I cancelled or never agreed to.\n\nCountry: [COUNTRY]\nCompany name: [NAME]\nCharge amount: [AMOUNT per month/year]\nTotal charged since issue began: [AMOUNT over X months]\nPayment method: [credit card / debit card — card network: Visa / Mastercard / Amex]\n\nWhat happened:\n- [e.g. I cancelled but charges continued / I was enrolled in auto-renewal without clear consent / free trial converted to paid without warning]\n\nCancellation date: [DATE]\nDo you have proof of cancellation? [yes — describe / no]\nCompany\'s response when contacted: [describe — e.g. partial refund offered, said cancellation did not go through]\n\nWhat I want: [full refund of all unauthorised charges / cancellation confirmed / both]',
      },
    ],
  },
  {
    id: 'tokenlegal',
    name: 'TokenLegal',
    tagline: 'Crypto tax & legal check',
    description: 'Describe your crypto activities and get a jurisdiction-specific tax and legal risk summary.',
    icon: 'Coins',
    color: 'bg-yellow-50',
    inputType: 'textarea',
    inputLabel: 'Describe your crypto situation or upload a transaction statement',
    inputPlaceholder: 'e.g. I am in Romania. I staked ETH in 2024 and earned ~2 ETH in rewards...',
    price: 1,
    quiz: [
      {
        id: 'country',
        question: 'What is your country of tax residence?',
        fieldLabel: 'Country of tax residence',
        type: 'text',
        placeholder: 'e.g. Germany, Romania, United Kingdom, United States',
        required: true,
      },
      {
        id: 'tax_year',
        question: 'Which tax year are you asking about?',
        fieldLabel: 'Tax year',
        type: 'text',
        placeholder: 'e.g. 2025, or "2024–2025 fiscal year"',
        required: true,
      },
      {
        id: 'activities',
        question: 'What crypto activities did you carry out?',
        fieldLabel: 'Crypto activities',
        type: 'multiselect',
        options: [
          'Buying and selling / trading',
          'Staking rewards',
          'Yield farming or liquidity pools',
          'NFT sales or purchases',
          'Airdrops received',
          'Crypto received as payment for work',
          'Mining',
          'Crypto-to-crypto swaps',
          'Other',
        ],
        required: true,
      },
      {
        id: 'gain_loss',
        question: 'What is your approximate net gain or loss?',
        fieldLabel: 'Approximate net gain / loss',
        type: 'text',
        placeholder: 'e.g. +€8,500 gain, or -€2,000 loss, or "unsure — need help calculating"',
        required: false,
      },
      {
        id: 'holding_period',
        question: 'How long did you hold the assets before selling?',
        fieldLabel: 'Holding period',
        type: 'select',
        options: [
          'All sold within 1 year of purchase',
          'Some held for over 1 year',
          'All held for over 1 year',
          'I have not sold — still holding',
          'Mix of different periods',
        ],
        required: true,
      },
      {
        id: 'records',
        question: 'Do you have full transaction records?',
        fieldLabel: 'Transaction records',
        type: 'select',
        options: [
          'Yes — complete records from all exchanges and wallets',
          'Partial — some exchanges or periods missing',
          'No — records are incomplete or unavailable',
        ],
        required: true,
      },
      {
        id: 'main_questions',
        question: 'What do you most need to know?',
        fieldLabel: 'Main questions',
        type: 'multiselect',
        options: [
          'What tax rate applies to my gains',
          'Which tax form or schedule to use',
          'Whether I can offset losses against gains',
          'Whether social or payroll tax applies',
          'Whether my activity is taxable at all',
          'What happens if I did not declare previously',
          'Are my records sufficient to file',
        ],
        required: true,
      },
    ],
    templates: [
      {
        label: '₿ Trading profits',
        text: 'I made profits from buying and selling cryptocurrency and need to understand my tax obligations.\n\nCountry of tax residence: [COUNTRY]\nTax year: [YEAR]\nCoins traded: [BTC / ETH / altcoins — specify]\nApproximate total proceeds from sales: [AMOUNT + local currency]\nApproximate total cost of coins sold: [AMOUNT + local currency]\nNet gain / loss: [AMOUNT]\nHolding periods: [all under 1 year / some over 1 year / all over 1 year]\n\nHave you reported crypto income before? [yes / no]\nDo you have full transaction records? [yes — from which exchange(s) / partial / no]\nOther relevant details: [e.g. crypto-to-crypto swaps, DeFi activity, losses to offset]\n\nMain questions I have:\n- [e.g. which tax category applies / what rate / which form to use / can I offset losses]',
      },
      {
        label: '🔒 Staking & yield',
        text: 'I earned cryptocurrency through staking, yield farming, or lending and need to understand my tax obligations.\n\nCountry of tax residence: [COUNTRY]\nTax year: [YEAR]\nPlatform / protocol: [e.g. Binance / Lido / Aave / Coinbase]\nActivity type: [proof-of-stake staking / liquidity pool / lending / other]\nCrypto received as rewards: [AMOUNT in crypto — e.g. 2 ETH]\nApproximate fiat value at time of receipt: [AMOUNT + local currency]\nHave you sold the rewards yet? [yes — at what price / no — current value approximately X]\n\nHave you reported this type of income before? [yes / no]\nFull transaction history available? [yes / partial / no]\n\nMain questions I have:\n- [e.g. is this income or capital gains / what rate applies / does social/payroll tax apply / which form to use]',
      },
      {
        label: '🖼️ NFT & DeFi activity',
        text: 'I have complex cryptocurrency activity including NFTs or DeFi and need a tax analysis.\n\nCountry of tax residence: [COUNTRY]\nTax year: [YEAR]\n\nActivity breakdown:\n- NFT sales: [number of transactions, total proceeds, total cost basis, net gain/loss]\n- DeFi / liquidity pools: [describe activity and approximate amounts]\n- Airdrops received: [yes / no — describe and approximate value]\n- Crypto received as payment for work: [yes / no — describe]\n\nHave you kept records of all transactions? [yes / partial / no — which exchanges/wallets]\nHave you reported crypto taxes before? [yes / no]\n\nMain questions I have:\n- [e.g. how are NFT profits taxed / do airdrops count as income at receipt / which form to use / can I offset losses across different activities]',
      },
    ],
  },
  {
    id: 'lexaudit',
    name: 'LexAudit',
    tagline: 'Crypto tax notice & audit response',
    description: 'Got a letter from the tax authority about your crypto? Paste or upload it and get the exact response deadline, severity, realistic exposure, and a ready-to-send reply letter in your jurisdiction.',
    icon: 'FileWarning',
    color: 'bg-orange-50',
    inputType: 'textarea',
    inputLabel: 'Paste the notice text or upload the PDF / photo',
    inputPlaceholder: 'Paste the full text of the notice — every line, header, reference number, and the date. Or upload the scan and add any context here.',
    price: 2,
    quiz: [
      {
        id: 'country',
        question: 'Which country issued the notice?',
        fieldLabel: 'Country / tax authority',
        type: 'text',
        placeholder: 'e.g. United States (IRS), United Kingdom (HMRC), Romania (ANAF), Spain (AEAT), Germany (Finanzamt)',
        required: true,
      },
      {
        id: 'notice',
        question: 'Paste the full notice text (or describe it if uploading a scan).',
        fieldLabel: 'Notice content',
        type: 'textarea',
        placeholder: 'Paste every line of the letter including the reference number, date, code sections cited, dollar/euro amounts, and named officer. The more complete, the more accurate the analysis.',
        required: true,
      },
      {
        id: 'received',
        question: 'When did you receive it?',
        fieldLabel: 'Date received',
        type: 'text',
        placeholder: 'e.g. 2026-05-12 (or "today", "two weeks ago")',
        required: true,
      },
      {
        id: 'period',
        question: 'Which tax years does the notice cover?',
        fieldLabel: 'Tax period covered',
        type: 'text',
        placeholder: 'e.g. 2021, 2020-2022, "not stated"',
        required: true,
      },
      {
        id: 'exposure',
        question: 'Roughly how much unreported crypto activity might this cover?',
        fieldLabel: 'Estimated unreported amount',
        type: 'select',
        options: [
          'Nothing unreported — I declared everything',
          'Under $10k / €10k / £10k equivalent',
          '$10k – $50k equivalent',
          '$50k – $250k equivalent',
          '$250k – $1M equivalent',
          'Over $1M equivalent',
          'I do not know',
        ],
        required: true,
      },
      {
        id: 'history',
        question: 'Have you reported crypto on your tax returns before?',
        fieldLabel: 'Compliance history',
        type: 'select',
        options: [
          'Yes — every year I traded',
          'Partially — some years, not others',
          'No — I have never reported crypto',
          'I have never filed any tax return for these years',
          'I am currently in a voluntary disclosure program',
        ],
        required: true,
      },
      {
        id: 'priorContact',
        question: 'Have you already replied or spoken to the authority about this?',
        fieldLabel: 'Prior contact about this matter',
        type: 'select',
        options: [
          'No — I have not responded yet',
          'I called them but did not commit to anything in writing',
          'I sent a written reply',
          'I admitted unreported income verbally or in writing',
          'I already hired a lawyer or tax advisor',
        ],
        required: true,
      },
      {
        id: 'extras',
        question: 'Anything else relevant?',
        fieldLabel: 'Extra context',
        type: 'textarea',
        placeholder: 'Optional: which exchanges, whether you used a VPN, whether you held on hardware wallets, whether you received an exchange data-sharing notification, anything that worries you.',
        required: false,
      },
    ],
    templates: [
      {
        label: '🇺🇸 IRS letter (US)',
        text: 'I received a letter from the IRS about my crypto.\n\nLetter type / reference: [CP2000 / Letter 6173 / Letter 6174-A / Letter 4564 / Notice of Deficiency / other]\nDate on the letter: [date]\nDate I received it: [date]\nTax year(s) covered: [years]\nAmount they propose to assess: [amount in USD if stated]\n\nFull text of the letter:\n[paste every line — header, reference number, addressee, body, deadline language, signature block]\n\nMy crypto activity for that period:\n[brief summary — which exchanges, approximate volume, whether reported]',
      },
      {
        label: '🇬🇧 HMRC letter (UK)',
        text: 'I received a letter from HMRC about my cryptoassets.\n\nLetter type: [nudge letter / Schedule 36 information notice / discovery assessment / COP9 / other]\nDate on the letter: [date]\nDate I received it: [date]\nTax year(s): [years]\n\nFull text of the letter:\n[paste every line]\n\nMy cryptoasset activity for that period:\n[brief summary]\nHave I filed a Self Assessment for these years? [yes / no / partial]',
      },
      {
        label: '🇷🇴 ANAF (Romania)',
        text: 'Am primit o notificare de la ANAF privind activitatea mea cu criptomonede.\n\nTip document: [aviz de verificare / decizie de impunere / proces-verbal de control / somație / înștiințare]\nData documentului: [data]\nData primirii: [data]\nAnii fiscali vizați: [ani]\nSumă propusă spre impunere (dacă este menționată): [sumă în RON]\n\nTextul complet al documentului:\n[paste]\n\nActivitatea mea cu criptomonede pentru perioada respectivă:\n[burse folosite, volum aproximativ, dacă a fost declarată în declarația unică]',
      },
      {
        label: '🇪🇸 AEAT (Spain)',
        text: 'He recibido una notificación de la AEAT sobre mi actividad con criptomonedas.\n\nTipo de documento: [requerimiento de información / propuesta de liquidación / acta de inspección / modelo 720/721 / otro]\nFecha del documento: [fecha]\nFecha de recepción: [fecha]\nEjercicios fiscales: [años]\n\nTexto completo:\n[paste]\n\nMi actividad con criptomonedas durante el período:\n[exchanges, volumen aproximado, si fue declarada]',
      },
      {
        label: '🇩🇪 Finanzamt (Germany)',
        text: 'Ich habe eine Aufforderung vom Finanzamt zu meiner Krypto-Aktivität erhalten.\n\nArt des Schreibens: [Aufforderung zur Mitarbeit / Steuerbescheid / Vorladung zur Steuerfahndung / sonstiges]\nDatum des Schreibens: [Datum]\nEingangsdatum: [Datum]\nVeranlagungszeiträume: [Jahre]\n\nGesamter Text:\n[paste]\n\nMeine Krypto-Aktivität in diesem Zeitraum:\n[Börsen, ungefähres Volumen, ob in der Steuererklärung angegeben]',
      },
      {
        label: '🌍 Other jurisdiction',
        text: 'I received a tax-authority notice about my crypto activity.\n\nCountry and authority: [e.g. France DGFiP / Italy Agenzia delle Entrate / Australia ATO / Canada CRA / India IT Department / other]\nLetter type: [as named in the document]\nDate on the letter: [date]\nDate I received it: [date]\nTax year(s) covered: [years]\nAmount mentioned (if any): [amount + currency]\n\nFull text of the letter:\n[paste every line]\n\nMy crypto activity for that period:\n[brief summary]\nHave I reported it? [yes / no / partial]',
      },
    ],
  },
  {
    id: 'docwizard',
    name: 'DocWizard',
    tagline: 'Any government form, explained',
    description: 'Describe or paste a government form and get a plain-language guide on how to fill it correctly.',
    icon: 'ScrollText',
    color: 'bg-teal-50',
    inputType: 'textarea',
    inputLabel: 'Describe the form or upload a photo of it',
    inputPlaceholder: 'e.g. I have to fill out a Form DS-160 (US visa application)...',
    price: 1,
    quiz: [
      {
        id: 'document_type',
        question: 'What type of document or process do you need help with?',
        fieldLabel: 'Document type',
        type: 'select',
        options: [
          'Visa application',
          'Tax return or declaration',
          'Residence or work permit',
          'Benefits or social security claim',
          'Business registration',
          'Driving licence (new, renewal, or exchange)',
          'Birth, marriage, or death registration',
          'Other government form',
        ],
        required: true,
      },
      {
        id: 'country',
        question: 'Which country or authority is this for?',
        fieldLabel: 'Country / authority',
        type: 'text',
        placeholder: 'e.g. United States — US Embassy, or France — Tax Authority (DGFiP)',
        required: true,
      },
      {
        id: 'form_name',
        question: 'Do you know the form name or number?',
        fieldLabel: 'Form name or number',
        type: 'text',
        placeholder: 'e.g. DS-160, Self Assessment, Formulaire CERFA 12753, or leave blank if unsure',
        required: false,
      },
      {
        id: 'confusion',
        question: 'Which part are you confused about?',
        fieldLabel: 'Specific confusion',
        type: 'textarea',
        placeholder: 'Describe the specific sections, fields, or requirements you are unsure how to answer — the more specific, the better',
        required: true,
      },
      {
        id: 'complicating_factors',
        question: 'Does your situation have any complications?',
        fieldLabel: 'Complicating factors',
        type: 'multiselect',
        options: [
          'Self-employed or freelancer',
          'Gaps in employment history',
          'Prior visa refusal or immigration issue',
          'Dual nationality',
          'Criminal record or caution',
          'Non-standard family situation',
          'Applying from outside the country',
          'None of the above',
        ],
        required: true,
      },
      {
        id: 'documents',
        question: 'What documents do you already have ready?',
        fieldLabel: 'Documents available',
        type: 'textarea',
        placeholder: 'e.g. Valid passport, bank statements for 3 months, employer letter, birth certificate — or describe what you are unsure you need',
        required: false,
      },
      {
        id: 'deadline',
        question: 'Is there a deadline for submission?',
        fieldLabel: 'Submission deadline',
        type: 'text',
        placeholder: 'e.g. 14 June 2026, or "must submit before my current visa expires on 1 July"',
        required: false,
      },
    ],
    templates: [
      {
        label: '✈️ Visa application',
        text: 'I need help understanding and completing a visa application correctly.\n\nVisa type: [tourist / business / student / family reunification / work / other]\nCountry I am applying to: [COUNTRY]\nMy nationality: [COUNTRY]\nCountry I currently live in: [COUNTRY]\nApplication method: [online portal / paper form / consulate appointment]\nForm name or number (if known): [e.g. DS-160 / Schengen Form C / other]\n\nSections I am confused about:\n1. [describe the specific field or section — e.g. "previous visa refusals" / "purpose of visit" / "financial means"]\n2. [another section if applicable]\n\nMy specific situation that may affect the application:\n- [e.g. self-employed / gaps in employment / prior visa refusal / dual nationality / family ties in destination country]\n\nDocuments I have / am unsure about: [list what you have and what you are not sure is needed]',
      },
      {
        label: '🏦 Tax return',
        text: 'I need guidance on completing my tax return correctly.\n\nCountry: [COUNTRY]\nTax year: [YEAR]\nForm / system: [e.g. Self Assessment / Form 1040 / Déclaration 2042 / other]\nMy income situation: [employed / self-employed / both / retired / investor]\n\nIncome sources this year:\n- Employment (PAYE/salary): [AMOUNT or "not applicable"]\n- Self-employment / freelance: [AMOUNT or "not applicable"]\n- Rental income: [AMOUNT or "not applicable"]\n- Investment / dividends: [AMOUNT or "not applicable"]\n- Other: [describe]\n\nExpenses / deductions I am claiming: [describe — e.g. home office / equipment / professional subscriptions]\nSpecific sections I am confused about: [describe]\nHave I filed this type of return before? [yes / no]\nDeadline: [DATE if known]',
      },
      {
        label: '🛂 Residence / work permit',
        text: 'I need to apply for a residence or work permit and need a step-by-step guide.\n\nCountry I am applying in: [COUNTRY]\nPermit type: [work permit / residence permit / permanent residency / family reunification / other]\nMy current nationality: [COUNTRY]\nMy current immigration status in this country: [tourist visa / student visa / already resident / just arrived / other]\n\nReason for application: [e.g. new job offer / marriage to local resident / study / long-term stay]\nEmployer or sponsor: [yes — company name / no]\nHow long have I been in this country: [X months / years / not yet arrived]\n\nSpecific parts of the process I am confused about: [describe — e.g. which form to use / what documents are required / whether to apply inside or outside the country / processing time]\nIs this urgent? [yes — explain deadline / no]',
      },
    ],
  },
  {
    id: 'lexdraft',
    name: 'LexDraft',
    tagline: 'AI document generator',
    description: 'Describe any legal document you need and get a complete, lawyer-quality draft in seconds. NDAs, freelance contracts, demand letters, consent forms — all tailored to your jurisdiction.',
    icon: 'PenLine',
    color: 'bg-violet-50',
    inputType: 'textarea',
    inputLabel: 'Describe the document you need',
    inputPlaceholder: 'e.g. NDA between me and a freelancer, Romanian law, 6-month confidentiality, covers software development work for my startup...',
    price: 1,
    quiz: [
      {
        id: 'document_type',
        question: 'What type of document do you need?',
        fieldLabel: 'Document type',
        type: 'select',
        options: [
          'NDA (Non-Disclosure Agreement)',
          'Freelance or services contract',
          'Employment contract',
          'Demand letter',
          'Business partnership agreement',
          'Loan agreement',
          'Rental agreement',
          'Shareholder or investment agreement',
          'Other',
        ],
        required: true,
      },
      {
        id: 'jurisdiction',
        question: 'Which law should govern this document?',
        fieldLabel: 'Governing law / jurisdiction',
        type: 'text',
        placeholder: 'e.g. English law, Romanian law, California (US) — or "not sure" for a general international template',
        required: true,
      },
      {
        id: 'party1',
        question: 'Who is Party 1? (usually you or your company)',
        fieldLabel: 'Party 1',
        type: 'text',
        placeholder: 'e.g. My startup "Lexon Ltd" as the disclosing party, or "me, John Smith, as the service provider"',
        required: true,
      },
      {
        id: 'party2',
        question: 'Who is Party 2? (the other side)',
        fieldLabel: 'Party 2',
        type: 'text',
        placeholder: 'e.g. A freelance developer named Ana Pop, or "client company XYZ Srl"',
        required: true,
      },
      {
        id: 'purpose',
        question: 'What is the purpose of this document?',
        fieldLabel: 'Purpose and context',
        type: 'textarea',
        placeholder: 'Briefly describe the business relationship and what this document needs to govern or protect',
        required: true,
      },
      {
        id: 'key_terms',
        question: 'What are the key commercial terms?',
        fieldLabel: 'Key terms',
        type: 'textarea',
        placeholder: 'e.g. 12-month confidentiality, mutual NDA, IP transfers to client on payment, £3,500 total fee, 50% upfront, 30-day payment terms, 30-day termination notice',
        required: false,
      },
      {
        id: 'special_clauses',
        question: 'Any special clauses needed?',
        fieldLabel: 'Special clauses',
        type: 'text',
        placeholder: 'e.g. arbitration clause, non-solicitation of employees, liability cap at €10,000, no subcontracting',
        required: false,
      },
    ],
    templates: [
      {
        label: '🤫 NDA',
        text: 'I need a Non-Disclosure Agreement drafted.\n\nJurisdiction / governing law: [COUNTRY]\nParty 1 (disclosing party): [my name / company name and role — e.g. "my startup as the disclosing party"]\nParty 2 (receiving party): [other party name and role — e.g. "a freelance developer"]\n\nWhat confidential information needs protecting:\n- [e.g. source code / business strategy / client data / product roadmap / financial information]\n\nKey terms I need:\n- Confidentiality period: [X months / years / indefinite]\n- Is this mutual (both parties share secrets) or one-way? [mutual / one-way]\n- Should work-for-hire / IP ownership be addressed? [yes / no]\n- Remedy for breach: [injunctive relief / damages / both]\n- Any non-solicitation clause needed? [yes / no]\n\nContext: [briefly describe the business relationship and why you need this NDA]',
      },
      {
        label: '💻 Freelance contract',
        text: 'I need a freelance services agreement drafted.\n\nJurisdiction / governing law: [COUNTRY]\nClient (commissioning party): [name / company]\nFreelancer / contractor: [name]\nServices to be performed: [describe the work — e.g. web development / logo design / copywriting]\n\nCommercial terms:\n- Total fee: [AMOUNT + currency]\n- Payment structure: [e.g. 50% upfront / milestone-based / on delivery / NET 30]\n- Project timeline: [X weeks / specific deadline]\n- Revision rounds included: [X rounds or unlimited]\n\nKey clauses I need:\n- IP / copyright ownership: [transfers to client on full payment / freelancer retains license / other]\n- Subcontracting: [permitted / not permitted]\n- Termination: [X days notice / for cause only / other]\n- Liability cap: [yes — limit to fee paid / no specific cap]\n- Confidentiality: [yes / no]\n- Dispute resolution: [court / arbitration — which jurisdiction]',
      },
      {
        label: '✉️ Demand letter',
        text: 'I need a formal legal demand letter drafted.\n\nJurisdiction / governing law: [COUNTRY]\nSender: [your name / company]\nRecipient: [name / company]\n\nNature of the dispute:\n- [e.g. unpaid invoice / breach of contract / property damage / failure to deliver / other]\n\nAmount demanded: [AMOUNT + currency]\nBasis for the claim: [describe — e.g. invoice issued on DATE for services delivered and accepted, payment due by DATE per contract]\nPrior attempts to resolve: [describe — informal emails, calls, how many, dates, responses received]\n\nWhat I want the letter to demand:\n- Payment / specific performance / both\n- Response deadline: [X days — e.g. 14 days]\n- Consequence if ignored: [legal proceedings / small claims court / credit reporting / other]\n\nTone required: [firm and professional / final warning / opening position]',
      },
    ],
  },
  {
    id: 'toscanner',
    name: 'ToScan',
    tagline: 'Any Terms of Service, exposed',
    description: 'Paste any website URL and get a trust score, top red flags with exact quotes, what data they collect, rights you waive, and what to do before agreeing.',
    icon: 'Link',
    color: 'bg-indigo-50',
    inputType: 'url',
    inputLabel: 'Website or Terms of Service URL',
    inputPlaceholder: 'https://airbnb.com',
    price: 1,
    templates: [
      {
        label: '🏠 Airbnb',
        text: 'https://www.airbnb.com/terms',
      },
      {
        label: '🎵 Spotify',
        text: 'https://www.spotify.com/legal/end-user-agreement/',
      },
      {
        label: '📱 TikTok',
        text: 'https://www.tiktok.com/legal/page/eea/terms-of-service/en',
      },
    ],
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}
