import type { Tool } from '../types';

export const TOOLS: Tool[] = [
  {
    id: 'signsafe',
    name: 'SignSafe',
    tagline: 'Contract risk scanner',
    description: 'Paste any contract and get a plain-language breakdown of dangerous clauses, hidden fees, and what you are actually signing away.',
    icon: 'FileText',
    color: 'bg-emerald-50',
    inputType: 'textarea',
    inputLabel: 'Paste your contract text',
    inputPlaceholder: 'Paste the full contract here...',
    price: 1,
  },
  {
    id: 'finebot',
    name: 'FineBot',
    tagline: 'Dispute any fine or ticket',
    description: 'Got a parking ticket or admin penalty? Get a ready-to-send dispute letter tailored to your jurisdiction in under 60 seconds.',
    icon: 'AlertTriangle',
    color: 'bg-amber-50',
    inputType: 'form',
    inputLabel: 'Describe your fine',
    inputPlaceholder: 'e.g. Parking fine, €80, issued in Lisbon Portugal on 15 May 2026. I was parked for 10 minutes while unloading...',
    price: 1,
  },
  {
    id: 'tenantshield',
    name: 'TenantShield',
    tagline: 'Know your rental rights',
    description: 'Describe your landlord issue and get your exact legal rights plus a templated demand letter.',
    icon: 'Home',
    color: 'bg-purple-50',
    inputType: 'textarea',
    inputLabel: 'Describe your rental issue',
    inputPlaceholder: 'e.g. My landlord in Berlin refuses to return my €1200 deposit after I moved out 6 weeks ago. The apartment was in perfect condition...',
    price: 1,
  },
  {
    id: 'workershield',
    name: 'WorkerShield',
    tagline: 'Employment rights checker',
    description: 'Describe what happened at work — wrongful termination, unpaid overtime, or harassment — and get a legal action plan.',
    icon: 'Briefcase',
    color: 'bg-blue-50',
    inputType: 'textarea',
    inputLabel: 'Describe your work situation',
    inputPlaceholder: 'e.g. I was fired by email with no notice after 3 years at the company in the UK. I was never given a written contract...',
    price: 1,
  },
  {
    id: 'refundforce',
    name: 'RefundForce',
    tagline: 'Force a refund or chargeback',
    description: 'Describe your consumer dispute and get the exact legal template and escalation path to force a refund.',
    icon: 'Receipt',
    color: 'bg-red-50',
    inputType: 'textarea',
    inputLabel: 'Describe your consumer dispute',
    inputPlaceholder: 'e.g. I bought a laptop from an online store in Italy 3 weeks ago. It arrived broken. They are refusing to refund me...',
    price: 1,
  },
  {
    id: 'tokenlegal',
    name: 'TokenLegal',
    tagline: 'Crypto tax & legal check',
    description: 'Describe your crypto activities and get a jurisdiction-specific tax and legal risk summary.',
    icon: 'Coins',
    color: 'bg-yellow-50',
    inputType: 'textarea',
    inputLabel: 'Describe your crypto situation',
    inputPlaceholder: 'e.g. I am in Romania. I staked ETH in 2024 and earned ~2 ETH in rewards. I also sold some BTC for a profit of ~€5000...',
    price: 1,
  },
  {
    id: 'docwizard',
    name: 'DocWizard',
    tagline: 'Any government form, explained',
    description: 'Describe or paste a government form and get a plain-language guide on how to fill it correctly.',
    icon: 'ScrollText',
    color: 'bg-teal-50',
    inputType: 'textarea',
    inputLabel: 'Describe or paste the form',
    inputPlaceholder: 'e.g. I have to fill out a Form DS-160 (US visa application). I am confused about the travel history section...',
    price: 1,
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}
